-- Update products table based on Inventory-Tracking.csv data
BEGIN;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS begin_inventory NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS purchases NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS sales_units NUMERIC(10,2);

WITH category_input(name) AS (
  VALUES
  ('CLOTH:'),
  ('BLOUSE SR/CDT.'),
  ('POLO SHIRT (Combi)'),
  ('BLACK ADULT POLO SHIRT'),
  ('MEN''S BLACK POLO'),
  ('FUN T-SHIRT'),
  ('PLAIN GREEN SKIRT'),
  ('RINNA BLOUSE'),
  ('RAGLAN SHIRT'),
  ('FUN SHIRT Raglan-Everyway'),
  ('FUN SHIRT Professionals - White'),
  ('1940 Anniv. Shirt Black'),
  ('1940 Anniv. Shirt White'),
  ('RTW GIRLS:'),
  ('T-SHIRTS:'),
  ('ADULT JACKET'),
  ('GSP TERNO (SET)'),
  ('VEST - WOOL'),
  ('VEST - WOOL EMBRO'),
  ('Green Pants-Wool'),
  ('Green Pants Wool (old price)'),
  ('JOGGING PANTS'),
  ('BERMUDA SHORTS (Star & Junior)'),
  ('BERMUDA SHORT-Senior & Cadet'),
  ('SCARF'),
  ('NYLON BELT'),
  ('SOCKS'),
  ('STRIPS'),
  ('SASH'),
  ('CAPS'),
  ('PINS'),
  ('FACE MASK'),
  ('Keychain-Gespie'),
  ('GESPIE Doll (big)'),
  ('Rag Doll Twinkler (S)'),
  ('MANUAL (Old)'),
  ('HANDBOOK (Old)'),
  ('MANUAL (New)'),
  ('HANDBOOK (New)'),
  ('A Camping we go'),
  ('Songbook'),
  ('Goodwill Pouch'),
  ('Magic Carpet'),
  ('BADGES'),
  ('TWINKLER'),
  ('STAR'),
  ('JUNIOR'),
  ('SENIOR'),
  ('CADET')
),
inserted_categories AS (
  INSERT INTO public.product_categories (name)
  SELECT name FROM category_input
  ON CONFLICT (name) DO NOTHING
  RETURNING id, name
),
all_categories AS (
  SELECT id, name FROM inserted_categories
  UNION
  SELECT id, name FROM public.product_categories
  WHERE name IN (SELECT name FROM category_input)
),
inventory_data (sku, product_name, size, category_name, cost_price, selling_price, begin_inventory, purchases, sales_units, end_inventory) AS (
  VALUES
  ('INV-CLOTH-POLYESTER', 'CLOTH:', 'Polyester', 'CLOTH:', 148.75, 193, 51, NULL, NULL, 51),
  ('INV-CLOTH-KEYSLEY', 'CLOTH:', 'Keysley', 'CLOTH:', 130.9, 170, 26.5, NULL, NULL, 26.5),
  ('INV-CLOTH-PLAIN-GREEN', 'CLOTH:', 'Plain Green', 'CLOTH:', 107.1, 140, 22, NULL, NULL, 22),
  ('INV-CLOTH-PEACH-TWILL', 'CLOTH:', 'Peach Twill', 'CLOTH:', 126.5, 153, 14, NULL, NULL, 14),
  ('INV-BLOUSE-SR-CDT-18', 'BLOUSE SR/CDT.', '#18', 'BLOUSE SR/CDT.', 260, 286, NULL, NULL, NULL, 0),
  ('INV-BLOUSE-SR-CDT-SMALL', 'BLOUSE SR/CDT.', 'Small', 'BLOUSE SR/CDT.', 274, 301, 29, NULL, 14, 15),
  ('INV-BLOUSE-SR-CDT-MEDIUM', 'BLOUSE SR/CDT.', 'Medium', 'BLOUSE SR/CDT.', 274, 301, 29, NULL, 13, 16),
  ('INV-BLOUSE-SR-CDT-LARGE', 'BLOUSE SR/CDT.', 'Large', 'BLOUSE SR/CDT.', 286, 315, 67, NULL, 4, 63),
  ('INV-BLOUSE-SR-CDT-X-LARGE', 'BLOUSE SR/CDT.', 'X-Large', 'BLOUSE SR/CDT.', 297, 327, 60, NULL, 1, 59),
  ('INV-BLOUSE-SR-CDT-2XL', 'BLOUSE SR/CDT.', '2XL', 'BLOUSE SR/CDT.', 324, 356, NULL, NULL, NULL, 0),
  ('INV-POLO-SHIRT-COMBI-2XL', 'POLO SHIRT (Combi)', '2XL', 'POLO SHIRT (Combi)', 160.65, 310, 10, NULL, NULL, 10),
  ('INV-BLACK-ADULT-POLO-SHI-SMALL', 'BLACK ADULT POLO SHIRT', 'Small', 'BLACK ADULT POLO SHIRT', 333.2, 435, 93, NULL, 1, 92),
  ('INV-BLACK-ADULT-POLO-SHI-MEDIUM', 'BLACK ADULT POLO SHIRT', 'Medium', 'BLACK ADULT POLO SHIRT', 333.2, 435, 3, NULL, NULL, 3),
  ('INV-BLACK-ADULT-POLO-SHI-LARGE', 'BLACK ADULT POLO SHIRT', 'Large', 'BLACK ADULT POLO SHIRT', 345.1, 450, 41, NULL, 1, 40),
  ('INV-BLACK-ADULT-POLO-SHI-X-LARGE', 'BLACK ADULT POLO SHIRT', 'X-Large', 'BLACK ADULT POLO SHIRT', 345.1, 450, 21, NULL, NULL, 21),
  ('INV-BLACK-ADULT-POLO-SHI-2XL', 'BLACK ADULT POLO SHIRT', '2XL', 'BLACK ADULT POLO SHIRT', 357, 470, 4, NULL, NULL, 4),
  ('INV-BLACK-ADULT-POLO-SHI-3XL', 'BLACK ADULT POLO SHIRT', '3XL', 'BLACK ADULT POLO SHIRT', 357, 480, 4, NULL, NULL, 4),
  ('INV-BLACK-ADULT-POLO-SHI-4XL', 'BLACK ADULT POLO SHIRT', '4XL', 'BLACK ADULT POLO SHIRT', 348.5, 490, 0, NULL, NULL, 0),
  ('INV-BLACK-ADULT-POLO-SHI-5XL', 'BLACK ADULT POLO SHIRT', '5XL', 'BLACK ADULT POLO SHIRT', 348.5, 500, 0, NULL, NULL, 0),
  ('INV-MEN-S-BLACK-POLO-MEDIUM', 'MEN''S BLACK POLO', 'MEDIUM', 'MEN''S BLACK POLO', 333.75, 395, 0, NULL, NULL, 0),
  ('INV-MEN-S-BLACK-POLO-LARGE', 'MEN''S BLACK POLO', 'LARGE', 'MEN''S BLACK POLO', 357, 420, 0, NULL, NULL, 0),
  ('INV-FUN-T-SHIRT-SMALL', 'FUN T-SHIRT', 'Small', 'FUN T-SHIRT', 212.5, 250, 5, NULL, NULL, 5),
  ('INV-FUN-T-SHIRT-MEDIUM', 'FUN T-SHIRT', 'Medium', 'FUN T-SHIRT', 212.5, 250, 12, NULL, NULL, 12),
  ('INV-FUN-T-SHIRT-LARGE', 'FUN T-SHIRT', 'Large', 'FUN T-SHIRT', 212.5, 250, 1, NULL, NULL, 1),
  ('INV-PLAIN-GREEN-SKIRT-SMALL', 'PLAIN GREEN SKIRT', 'Small', 'PLAIN GREEN SKIRT', 179, 197, 40, NULL, 12, 28),
  ('INV-PLAIN-GREEN-SKIRT-MEDIUM', 'PLAIN GREEN SKIRT', 'Medium', 'PLAIN GREEN SKIRT', 191, 210, 50, NULL, 10, 40),
  ('INV-PLAIN-GREEN-SKIRT-LARGE', 'PLAIN GREEN SKIRT', 'Large', 'PLAIN GREEN SKIRT', 197, 217, 32, NULL, 6, 26),
  ('INV-PLAIN-GREEN-SKIRT-X-LARGE', 'PLAIN GREEN SKIRT', 'X-Large', 'PLAIN GREEN SKIRT', 197, 217, 21, NULL, 4, 17),
  ('INV-PLAIN-GREEN-SKIRT-2XL', 'PLAIN GREEN SKIRT', '2XL', 'PLAIN GREEN SKIRT', 244, 268, NULL, NULL, NULL, 0),
  ('INV-RINNA-BLOUSE-SMALL', 'RINNA BLOUSE', 'Small', 'RINNA BLOUSE', 392, 431, 20, NULL, 1, 19),
  ('INV-RINNA-BLOUSE-MEDIUM', 'RINNA BLOUSE', 'Medium', 'RINNA BLOUSE', 392, 431, 12, NULL, NULL, 12),
  ('INV-RINNA-BLOUSE-LARGE', 'RINNA BLOUSE', 'Large', 'RINNA BLOUSE', 420, 462, 13, NULL, NULL, 13),
  ('INV-RINNA-BLOUSE-XL', 'RINNA BLOUSE', 'XL', 'RINNA BLOUSE', 420, 462, 1, NULL, NULL, 1),
  ('INV-RINNA-BLOUSE-2XL', 'RINNA BLOUSE', '2XL', 'RINNA BLOUSE', 448, 493, 0, NULL, NULL, 0),
  ('INV-RAGLAN-SHIRT-SMALL', 'RAGLAN SHIRT', 'Small', 'RAGLAN SHIRT', 178.5, 230, 1, NULL, NULL, 1),
  ('INV-RAGLAN-SHIRT-MEDIUM', 'RAGLAN SHIRT', 'Medium', 'RAGLAN SHIRT', 178.5, 230, 0, NULL, NULL, 0),
  ('INV-RAGLAN-SHIRT-LARGE', 'RAGLAN SHIRT', 'Large', 'RAGLAN SHIRT', 178.5, 230, 0, NULL, NULL, 0),
  ('INV-RAGLAN-SHIRT-X-LARGE', 'RAGLAN SHIRT', 'X-Large', 'RAGLAN SHIRT', 178.5, 230, 0, NULL, NULL, 0),
  ('INV-RAGLAN-SHIRT-2XL', 'RAGLAN SHIRT', '2XL', 'RAGLAN SHIRT', 178.5, 230, 0, NULL, NULL, 0),
  ('INV-FUN-SHIRT-RAGLAN-EVE-MEDIUM', 'FUN SHIRT Raglan-Everyway', 'Medium', 'FUN SHIRT Raglan-Everyway', 195.5, 253, 1, NULL, NULL, 1),
  ('INV-FUN-SHIRT-RAGLAN-EVE-LARGE', 'FUN SHIRT Raglan-Everyway', 'Large', 'FUN SHIRT Raglan-Everyway', 204, 264, 2, NULL, NULL, 2),
  ('INV-FUN-SHIRT-RAGLAN-EVE-X-LARGE', 'FUN SHIRT Raglan-Everyway', 'X-Large', 'FUN SHIRT Raglan-Everyway', 204, 264, 2, NULL, NULL, 2),
  ('INV-FUN-SHIRT-RAGLAN-EVE-2XL', 'FUN SHIRT Raglan-Everyway', '2XL', 'FUN SHIRT Raglan-Everyway', 212.5, 275, 7, NULL, NULL, 7),
  ('INV-FUN-SHIRT-RAGLAN-EVE-3XL', 'FUN SHIRT Raglan-Everyway', '3Xl', 'FUN SHIRT Raglan-Everyway', 212.5, 275, 18, NULL, NULL, 18),
  ('INV-FUN-SHIRT-RAGLAN-EVE-4XL', 'FUN SHIRT Raglan-Everyway', '4XL', 'FUN SHIRT Raglan-Everyway', 221, 286, 0, NULL, NULL, 0),
  ('INV-FUN-SHIRT-RAGLAN-EVE-5XL', 'FUN SHIRT Raglan-Everyway', '5XL', 'FUN SHIRT Raglan-Everyway', 221, 286, 0, NULL, NULL, 0),
  ('INV-FUN-SHIRT-PROFESSION-LARGE', 'FUN SHIRT Professionals - White', 'Large', 'FUN SHIRT Professionals - White', 170, 200, 0, NULL, NULL, 0),
  ('INV-FUN-SHIRT-PROFESSION-X-LARGE', 'FUN SHIRT Professionals - White', 'X-Large', 'FUN SHIRT Professionals - White', 170, 200, 0, NULL, NULL, 0),
  ('INV-FUN-SHIRT-PROFESSION-3XL', 'FUN SHIRT Professionals - White', '3Xl', 'FUN SHIRT Professionals - White', 178.5, 210, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-BLA-SMALL', '1940 Anniv. Shirt Black', 'SMALL', '1940 Anniv. Shirt Black', 196.35, 255, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-BLA-MEDIUM', '1940 Anniv. Shirt Black', 'MEDIUM', '1940 Anniv. Shirt Black', 196.35, 255, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-BLA-LARGE', '1940 Anniv. Shirt Black', 'Large', '1940 Anniv. Shirt Black', 208.25, 270, 1, NULL, NULL, 1),
  ('INV-1940-ANNIV-SHIRT-BLA-XL', '1940 Anniv. Shirt Black', 'XL', '1940 Anniv. Shirt Black', 208.25, 270, 4, NULL, 1, 3),
  ('INV-1940-ANNIV-SHIRT-BLA-2XL', '1940 Anniv. Shirt Black', '2XL', '1940 Anniv. Shirt Black', 220.15, 285, 1, NULL, NULL, 1),
  ('INV-1940-ANNIV-SHIRT-BLA-3XL', '1940 Anniv. Shirt Black', '3XL', '1940 Anniv. Shirt Black', 220.15, 285, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-BLA-5XL', '1940 Anniv. Shirt Black', '5XL', '1940 Anniv. Shirt Black', 232.05, 300, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-SMALL', '1940 Anniv. Shirt White', 'SMALL', '1940 Anniv. Shirt White', 142.8, 185, 18, NULL, NULL, 18),
  ('INV-1940-ANNIV-SHIRT-WHI-MEDIUM', '1940 Anniv. Shirt White', 'MEDIUM', '1940 Anniv. Shirt White', 142.8, 185, 7, NULL, NULL, 7),
  ('INV-1940-ANNIV-SHIRT-WHI-LARGE', '1940 Anniv. Shirt White', 'Large', '1940 Anniv. Shirt White', 154.7, 200, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-XL', '1940 Anniv. Shirt White', 'XL', '1940 Anniv. Shirt White', 154.7, 200, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-2XL', '1940 Anniv. Shirt White', '2XL', '1940 Anniv. Shirt White', 166.6, 215, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-3XL', '1940 Anniv. Shirt White', '3XL', '1940 Anniv. Shirt White', 166.6, 215, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-4XL', '1940 Anniv. Shirt White', '4XL', '1940 Anniv. Shirt White', 178.5, 231, 0, NULL, NULL, 0),
  ('INV-1940-ANNIV-SHIRT-WHI-5XL', '1940 Anniv. Shirt White', '5XL', '1940 Anniv. Shirt White', 178.5, 231, 0, NULL, NULL, 0),
  ('INV-RTW-GIRLS-TWINKLER-S', 'RTW GIRLS:', 'Twinkler-S', 'RTW GIRLS:', 318, 350, 45, NULL, 2, 43),
  ('INV-RTW-GIRLS-TWINKLER-M', 'RTW GIRLS:', 'Twinkler-M', 'RTW GIRLS:', 318, 350, 0, NULL, NULL, 0),
  ('INV-RTW-GIRLS-TWINKLER-L', 'RTW GIRLS:', 'Twinkler-L', 'RTW GIRLS:', 353, 388, 0, NULL, NULL, 0),
  ('INV-RTW-GIRLS-TWINKLER-XL', 'RTW GIRLS:', 'Twinkler-XL', 'RTW GIRLS:', 371, 408, 0, NULL, NULL, 0),
  ('INV-RTW-GIRLS-8', 'RTW GIRLS:', '8', 'RTW GIRLS:', 301, 331, 14, NULL, 1, 13),
  ('INV-RTW-GIRLS-10', 'RTW GIRLS:', '10', 'RTW GIRLS:', 309, 340, 31, NULL, NULL, 31),
  ('INV-RTW-GIRLS-12', 'RTW GIRLS:', '12', 'RTW GIRLS:', 318, 350, 37, NULL, NULL, 37),
  ('INV-RTW-GIRLS-14', 'RTW GIRLS:', '14', 'RTW GIRLS:', 375, 413, 34, NULL, NULL, 34),
  ('INV-RTW-GIRLS-16', 'RTW GIRLS:', '16', 'RTW GIRLS:', 392, 431, 26, NULL, NULL, 26),
  ('INV-RTW-GIRLS-18', 'RTW GIRLS:', '18', 'RTW GIRLS:', 410, 451, 33, NULL, NULL, 33),
  ('INV-RTW-GIRLS-20', 'RTW GIRLS:', '20', 'RTW GIRLS:', 448, 493, 15, NULL, NULL, 15),
  ('INV-RTW-GIRLS-22', 'RTW GIRLS:', '22', 'RTW GIRLS:', 483, 531, 0, NULL, NULL, 0),
  ('INV-T-SHIRTS-10', 'T-SHIRTS:', '10', 'T-SHIRTS:', 59.5, 80, 33, NULL, 3, 30),
  ('INV-T-SHIRTS-12', 'T-SHIRTS:', '12', 'T-SHIRTS:', 63.75, 85, 41, NULL, 4, 37),
  ('INV-T-SHIRTS-14', 'T-SHIRTS:', '14', 'T-SHIRTS:', 68, 90, 15, NULL, NULL, 15),
  ('INV-T-SHIRTS-16', 'T-SHIRTS:', '16', 'T-SHIRTS:', 72.25, 95, 179, NULL, NULL, 179),
  ('INV-T-SHIRTS-18', 'T-SHIRTS:', '18', 'T-SHIRTS:', 76.5, 100, 26, NULL, 4, 22),
  ('INV-T-SHIRTS-SMALL', 'T-SHIRTS:', 'Small', 'T-SHIRTS:', 85, 105, 1, NULL, NULL, 1),
  ('INV-T-SHIRTS-MEDIUM', 'T-SHIRTS:', 'Medium', 'T-SHIRTS:', 89.25, 115, 22, NULL, 12, 10),
  ('INV-T-SHIRTS-LARGE', 'T-SHIRTS:', 'Large', 'T-SHIRTS:', 97.75, 127, 69, NULL, 2, 67),
  ('INV-ADULT-JACKET-SMALL', 'ADULT JACKET', 'Small', 'ADULT JACKET', 637.5, 750, 0, NULL, NULL, 0),
  ('INV-ADULT-JACKET-MEDIUM', 'ADULT JACKET', 'Medium', 'ADULT JACKET', 637.5, 750, 0, NULL, NULL, 0),
  ('INV-GSP-TERNO-SET', 'GSP TERNO (SET)', NULL, 'GSP TERNO (SET)', 1428, 1680, 3, NULL, NULL, 3),
  ('INV-VEST-WOOL-SMALL', 'VEST - WOOL', 'Small', 'VEST - WOOL', 302.81, 395, 0, NULL, NULL, 0),
  ('INV-VEST-WOOL-MEDIUM', 'VEST - WOOL', 'Medium', 'VEST - WOOL', 302.81, 395, 0, NULL, NULL, 0),
  ('INV-VEST-WOOL-LARGE', 'VEST - WOOL', 'Large', 'VEST - WOOL', 302.81, 395, 12, NULL, NULL, 12),
  ('INV-VEST-WOOL-X-LARGE', 'VEST - WOOL', 'X-Large', 'VEST - WOOL', 302.81, 395, 6, NULL, NULL, 6),
  ('INV-VEST-WOOL-EMBRO-SMALL', 'VEST - WOOL EMBRO', 'Small', 'VEST - WOOL EMBRO', 393, 432, 16, NULL, 2, 14),
  ('INV-VEST-WOOL-EMBRO-MEDIUM', 'VEST - WOOL EMBRO', 'Medium', 'VEST - WOOL EMBRO', 393, 432, 18, NULL, 2, 16),
  ('INV-VEST-WOOL-EMBRO-LARGE', 'VEST - WOOL EMBRO', 'Large', 'VEST - WOOL EMBRO', 393, 432, 8, NULL, 2, 6),
  ('INV-VEST-WOOL-EMBRO-XL', 'VEST - WOOL EMBRO', 'XL', 'VEST - WOOL EMBRO', 415, 457, NULL, NULL, NULL, 0),
  ('INV-VEST-WOOL-EMBRO-2XL', 'VEST - WOOL EMBRO', '2XL', 'VEST - WOOL EMBRO', 415, 457, NULL, NULL, NULL, 0),
  ('INV-VEST-WOOL-EMBRO-3XL', 'VEST - WOOL EMBRO', '3XL', 'VEST - WOOL EMBRO', 438, 482, NULL, NULL, NULL, 0),
  ('INV-GREEN-PANTS-WOOL-SMALL', 'Green Pants-Wool', 'Small', 'Green Pants-Wool', 340, 440, 22, NULL, 1, 21),
  ('INV-GREEN-PANTS-WOOL-MEDIUM', 'Green Pants-Wool', 'Medium', 'Green Pants-Wool', 340, 440, 27, NULL, NULL, 27),
  ('INV-GREEN-PANTS-WOOL-LARGE', 'Green Pants-Wool', 'Large', 'Green Pants-Wool', 340, 440, 1, NULL, NULL, 1),
  ('INV-GREEN-PANTS-WOOL-XL', 'Green Pants-Wool', 'XL', 'Green Pants-Wool', 340, 470, 4, NULL, NULL, 4),
  ('INV-GREEN-PANTS-WOOL-XXL', 'Green Pants-Wool', 'XXL', 'Green Pants-Wool', 360.4, 470, 19, NULL, NULL, 19),
  ('INV-GREEN-PANTS-WOOL-OLD-X-LARGE', 'Green Pants Wool (old price)', 'X-Large', 'Green Pants Wool (old price)', 341.5, 420, NULL, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-16', 'JOGGING PANTS', '#16', 'JOGGING PANTS', 272, 350, 0, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-18', 'JOGGING PANTS', '#18', 'JOGGING PANTS', 314.5, 407, 9, NULL, 2, 7),
  ('INV-JOGGING-PANTS-20', 'JOGGING PANTS', '#20', 'JOGGING PANTS', 318.75, 413, 2, NULL, 3, -1),
  ('INV-JOGGING-PANTS-SMALL', 'JOGGING PANTS', 'Small', 'JOGGING PANTS', 323, 418, 0, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-MEDIUM', 'JOGGING PANTS', 'Medium', 'JOGGING PANTS', 327.25, 424, 0, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-LARGE', 'JOGGING PANTS', 'Large', 'JOGGING PANTS', 331.5, 429, 0, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-XL', 'JOGGING PANTS', 'XL', 'JOGGING PANTS', 335.75, 435, 0, NULL, NULL, 0),
  ('INV-JOGGING-PANTS-2XL', 'JOGGING PANTS', '2XL', 'JOGGING PANTS', 340, 440, 22, NULL, 2, 20),
  ('INV-BERMUDA-SHORTS-STAR--16-OLD-PRICE', 'BERMUDA SHORTS (Star & Junior)', '#16 (Old Price)', 'BERMUDA SHORTS (Star & Junior)', NULL, 189, 2, NULL, 2, NULL),
  ('INV-BERMUDA-SHORTS-STAR--16-NEW-PRICE', 'BERMUDA SHORTS (Star & Junior)', '#16 (New Price)', 'BERMUDA SHORTS (Star & Junior)', 180, 198, 32, NULL, 1, 31),
  ('INV-BERMUDA-SHORTS-STAR--18-OLD-PRICE', 'BERMUDA SHORTS (Star & Junior)', '#18 (Old Price)', 'BERMUDA SHORTS (Star & Junior)', NULL, 200, 2, NULL, 2, 0),
  ('INV-BERMUDA-SHORTS-STAR--18-NEW-PRICE', 'BERMUDA SHORTS (Star & Junior)', '#18 (New Price)', 'BERMUDA SHORTS (Star & Junior)', 189, 208, 45, NULL, NULL, 45),
  ('INV-BERMUDA-SHORTS-STAR--SMALL', 'BERMUDA SHORTS (Star & Junior)', 'Small', 'BERMUDA SHORTS (Star & Junior)', 206, 227, 31, NULL, NULL, 31),
  ('INV-BERMUDA-SHORTS-STAR--MEDIUM', 'BERMUDA SHORTS (Star & Junior)', 'Medium', 'BERMUDA SHORTS (Star & Junior)', 224, 246, 28, NULL, NULL, 28),
  ('INV-BERMUDA-SHORTS-STAR--LARGE', 'BERMUDA SHORTS (Star & Junior)', 'Large', 'BERMUDA SHORTS (Star & Junior)', 233, 256, 54, NULL, NULL, 54),
  ('INV-BERMUDA-SHORTS-STAR--XL', 'BERMUDA SHORTS (Star & Junior)', 'XL', 'BERMUDA SHORTS (Star & Junior)', 241, 265, NULL, NULL, NULL, 0),
  ('INV-BERMUDA-SHORTS-STAR--2XL', 'BERMUDA SHORTS (Star & Junior)', '2XL', 'BERMUDA SHORTS (Star & Junior)', 259, 285, NULL, NULL, NULL, 0),
  ('INV-BERMUDA-SHORT-SENIOR-SMALL', 'BERMUDA SHORT-Senior & Cadet', 'Small', 'BERMUDA SHORT-Senior & Cadet', 222, 244, 10, NULL, 1, 9),
  ('INV-BERMUDA-SHORT-SENIOR-MEDIUM', 'BERMUDA SHORT-Senior & Cadet', 'Medium', 'BERMUDA SHORT-Senior & Cadet', 238, 262, 28, NULL, 2, 26),
  ('INV-BERMUDA-SHORT-SENIOR-LARGE', 'BERMUDA SHORT-Senior & Cadet', 'Large', 'BERMUDA SHORT-Senior & Cadet', 245, 270, 27, NULL, 3, 24),
  ('INV-BERMUDA-SHORT-SENIOR-X-LARGE', 'BERMUDA SHORT-Senior & Cadet', 'X-Large', 'BERMUDA SHORT-Senior & Cadet', 253, 278, 61, NULL, 1, 60),
  ('INV-BERMUDA-SHORT-SENIOR-2XL', 'BERMUDA SHORT-Senior & Cadet', '2XL', 'BERMUDA SHORT-Senior & Cadet', 268, 295, 53, NULL, NULL, 53),
  ('INV-SCARF-PINK', 'SCARF', 'Pink', 'SCARF', 63.75, 85, 87, NULL, 6, 81),
  ('INV-SCARF-YELLOW', 'SCARF', 'Yellow', 'SCARF', 63.75, 85, 235, NULL, 1, 234),
  ('INV-SCARF-GOLDEN-YELLOW', 'SCARF', 'Golden Yellow', 'SCARF', 63.75, 85, 213, NULL, 6, 207),
  ('INV-SCARF-TANGERINE', 'SCARF', 'Tangerine', 'SCARF', 63.75, 85, 142, NULL, 30, 112),
  ('INV-SCARF-PURPLE', 'SCARF', 'Purple', 'SCARF', 63.75, 85, 80, NULL, 22, 58),
  ('INV-SCARF-ADULT', 'SCARF', 'Adult', 'SCARF', 416.5, 540, 17, NULL, 2, 15),
  ('INV-NYLON-BELT-SMALL', 'NYLON BELT', 'Small', 'NYLON BELT', 41.65, 55, 0, NULL, NULL, 0),
  ('INV-NYLON-BELT-MEDIUM', 'NYLON BELT', 'Medium', 'NYLON BELT', 44.2, 58, 6, NULL, 7, -1),
  ('INV-NYLON-BELT-LARGE', 'NYLON BELT', 'Large', 'NYLON BELT', 46.75, 61, 44, NULL, 16, 28),
  ('INV-NYLON-BELT-X-LARGE', 'NYLON BELT', 'X-Large', 'NYLON BELT', 47.6, 65, 66, NULL, 3, 63),
  ('INV-SOCKS-4-7', 'SOCKS', '#4 -7', 'SOCKS', 42.5, 55, 59, NULL, 7, 52),
  ('INV-SOCKS-7-10', 'SOCKS', '# 7-10', 'SOCKS', 46.75, 61, 59, NULL, NULL, 59),
  ('INV-SOCKS-8-11', 'SOCKS', '# 8-11', 'SOCKS', 46.75, 61, 79, NULL, NULL, 79),
  ('INV-SOCKS-9-12', 'SOCKS', '# 9-12', 'SOCKS', 46.75, 61, 40, NULL, 3, 37),
  ('INV-SOCKS-KNEE-SOCK', 'SOCKS', 'Knee Sock', 'SOCKS', 63.75, 83, 13, NULL, 2, 11),
  ('INV-STRIPS-ILOCOS-SUR', 'STRIPS', 'ILOCOS SUR', 'STRIPS', 5.1, 10, 83, NULL, 22, 61),
  ('INV-STRIPS-GSP', 'STRIPS', 'GSP', 'STRIPS', 5.95, 10, 67, NULL, 22, 45),
  ('INV-SASH-SMALL', 'SASH', 'Small', 'SASH', 81, 89, 0, NULL, NULL, 0),
  ('INV-SASH-MEDIUM', 'SASH', 'Medium', 'SASH', 87, 96, 163, NULL, 3, 160),
  ('INV-SASH-LARGE', 'SASH', 'Large', 'SASH', 94, 103, 194, NULL, 6, 188),
  ('INV-SASH-X-LARGE', 'SASH', 'X-Large', 'SASH', 97, 107, 143, NULL, 4, 139),
  ('INV-CAPS-SMALL', 'CAPS', 'Small', 'CAPS', 75.65, 98, 34, NULL, 2, 32),
  ('INV-CAPS-MEDIUM', 'CAPS', 'Medium', 'CAPS', 77.35, 100, 64, NULL, 8, 56),
  ('INV-CAPS-LARGE', 'CAPS', 'Large', 'CAPS', 82.66, 110, 96, NULL, 8, 88),
  ('INV-PINS-TWINKLER', 'PINS', 'Twinkler', 'PINS', 27.5, 31, 48, NULL, 2, 46),
  ('INV-PINS-STAR', 'PINS', 'Star', 'PINS', 27.5, 31, 119, NULL, 1, 118),
  ('INV-PINS-JUNIOR', 'PINS', 'Junior', 'PINS', 27.5, 31, 198, NULL, NULL, 198),
  ('INV-PINS-SENIOR-NEW-PRICE', 'PINS', 'Senior (New Price)', 'PINS', NULL, 35, 193, NULL, 1, 192),
  ('INV-PINS-SENIOR-OLD-PRICE', 'PINS', 'Senior (Old Price)', 'PINS', 27.5, 31, 24, NULL, 24, 0),
  ('INV-PINS-CADET', 'PINS', 'Cadet', 'PINS', 27.5, 31, 79, NULL, 8, 71),
  ('INV-PINS-FIELD-ADVISER', 'PINS', 'Field Adviser', 'PINS', 41.01, 53, 1, NULL, 1, 0),
  ('INV-PINS-TROOP-LEADER', 'PINS', 'Troop Leader', 'PINS', 27.5, 31, 148, NULL, NULL, 148),
  ('INV-PINS-COUNCIL-BOARD', 'PINS', 'Council Board', 'PINS', 55.25, 72, 18, NULL, 3, 15),
  ('INV-PINS-DISTRICT-COMMITTEE', 'PINS', 'District Committee', 'PINS', 19.13, 25, 49, NULL, NULL, 49),
  ('INV-PINS-BRGY-COMMITTEE', 'PINS', 'Brgy. Committee', 'PINS', 19.13, 25, 90, NULL, NULL, 90),
  ('INV-PINS-WORLD-PIN', 'PINS', 'World Pin', 'PINS', 34, 50, 162, NULL, 33, 129),
  ('INV-PINS-PIN-HOLDER', 'PINS', 'Pin Holder', 'PINS', 28.5, 31, 135, NULL, 9, 126),
  ('INV-FACE-MASK-80TH-ANNIV', 'FACE MASK', '80th Anniv.', 'FACE MASK', 32.3, 40, 194, NULL, NULL, 194),
  ('INV-FACE-MASK-BATIK', 'FACE MASK', 'Batik', 'FACE MASK', 25.5, 35, 40, NULL, NULL, 40),
  ('INV-KEYCHAIN-GESPIE', 'Keychain-Gespie', NULL, 'Keychain-Gespie', 26.78, 35, 69, NULL, NULL, 69),
  ('INV-GESPIE-DOLL-BIG', 'GESPIE Doll (big)', NULL, 'GESPIE Doll (big)', 250, 275, NULL, NULL, NULL, 0),
  ('INV-RAG-DOLL-TWINKLER-S', 'Rag Doll Twinkler (S)', NULL, 'Rag Doll Twinkler (S)', 225, 248, 15, NULL, 4, 11),
  ('INV-MANUAL-OLD-TWINKLER', 'MANUAL (Old)', 'Twinkler', 'MANUAL (Old)', 34.42, 45, 55, NULL, NULL, 55),
  ('INV-MANUAL-OLD-STAR', 'MANUAL (Old)', 'Star', 'MANUAL (Old)', 55.08, 72, 1, NULL, NULL, 1),
  ('INV-MANUAL-OLD-JUNIOR', 'MANUAL (Old)', 'Junior', 'MANUAL (Old)', 88.74, 116, 8, NULL, NULL, 8),
  ('INV-MANUAL-OLD-SENIOR', 'MANUAL (Old)', 'Senior', 'MANUAL (Old)', 97.16, 127, 8, NULL, NULL, 8),
  ('INV-HANDBOOK-OLD-TWINKLER', 'HANDBOOK (Old)', 'Twinkler', 'HANDBOOK (Old)', 27.2, 40, 21, NULL, NULL, 21),
  ('INV-HANDBOOK-OLD-STAR', 'HANDBOOK (Old)', 'Star', 'HANDBOOK (Old)', 27.2, 75, 3, NULL, NULL, 3),
  ('INV-HANDBOOK-OLD-JUNIOR', 'HANDBOOK (Old)', 'Junior', 'HANDBOOK (Old)', 27.2, 40, 0, NULL, NULL, 0),
  ('INV-HANDBOOK-OLD-SENIOR', 'HANDBOOK (Old)', 'Senior', 'HANDBOOK (Old)', 97.16, 83, 3, NULL, NULL, 3),
  ('INV-MANUAL-NEW-TWINKLER', 'MANUAL (New)', 'Twinkler', 'MANUAL (New)', 145, 160, 6, NULL, NULL, 6),
  ('INV-MANUAL-NEW-STAR', 'MANUAL (New)', 'Star', 'MANUAL (New)', 119, 131, 10, NULL, NULL, 10),
  ('INV-MANUAL-NEW-JUNIOR', 'MANUAL (New)', 'Junior', 'MANUAL (New)', 161, 177, 57, NULL, NULL, 57),
  ('INV-MANUAL-NEW-SENIOR', 'MANUAL (New)', 'Senior', 'MANUAL (New)', 196, 216, 0, NULL, NULL, 0),
  ('INV-MANUAL-NEW-CADET', 'MANUAL (New)', 'Cadet', 'MANUAL (New)', 236, 260, 5, NULL, NULL, 5),
  ('INV-HANDBOOK-NEW-TWINKLER', 'HANDBOOK (New)', 'Twinkler', 'HANDBOOK (New)', 46.75, 65, 78, NULL, NULL, 78),
  ('INV-HANDBOOK-NEW-STAR', 'HANDBOOK (New)', 'Star', 'HANDBOOK (New)', 84.15, 110, 45, NULL, NULL, 45),
  ('INV-HANDBOOK-NEW-JUNIOR', 'HANDBOOK (New)', 'Junior', 'HANDBOOK (New)', 46.5, 62, 0, NULL, NULL, 0),
  ('INV-HANDBOOK-NEW-SENIOR', 'HANDBOOK (New)', 'Senior', 'HANDBOOK (New)', 106.25, 140, 26, NULL, 1, 25),
  ('INV-HANDBOOK-NEW-CADET', 'HANDBOOK (New)', 'Cadet', 'HANDBOOK (New)', 97, 107, 0, NULL, NULL, 0),
  ('INV-A-CAMPING-WE-GO', 'A Camping we go', NULL, 'A Camping we go', 42.5, 55, 55, NULL, NULL, 55),
  ('INV-SONGBOOK', 'Songbook', NULL, 'Songbook', 39.78, 52, 10, NULL, NULL, 10),
  ('INV-GOODWILL-POUCH', 'Goodwill Pouch', NULL, 'Goodwill Pouch', 51, 60, 8, NULL, NULL, 8),
  ('INV-GOODWILL-POUCH-PER-PIECE-P11-00', 'Goodwill Pouch', 'Per Piece (P11.00)', 'Goodwill Pouch', 8, 11, -280, 360, 80, 0),
  ('INV-GOODWILL-POUCH-PER-PIECE-P9-00', 'Goodwill Pouch', 'Per Piece (P9.00)', 'Goodwill Pouch', 8, 9, 0, 60, 60, 0),
  ('INV-GOODWILL-POUCH-PER-CASE-P520-00', 'Goodwill Pouch', 'Per Case (P520.00)', 'Goodwill Pouch', 8, 8.67, 0, 240, 240, 0),
  ('INV-GOODWILL-POUCH-PER-CASE-P530-00', 'Goodwill Pouch', 'Per Case (P530.00)', 'Goodwill Pouch', 8, 8.83, 0, 1140, 1140, 0),
  ('INV-MAGIC-CARPET', 'Magic Carpet', NULL, 'Magic Carpet', 560, 620, 1, NULL, NULL, 1),
  ('INV-MAGIC-CARPET-2', 'Magic Carpet', NULL, 'Magic Carpet', 654.5, 847, 9, NULL, 1, 8),
  ('INV-BADGES-YUNGA-ENDING-HUNGER', 'BADGES', 'Yunga-Ending Hunger', 'BADGES', 10, 10, 19, NULL, NULL, 19),
  ('INV-BADGES-THINKING-DAY-2019', 'BADGES', 'Thinking Day 2019', 'BADGES', 10, 10, 339, NULL, NULL, 339),
  ('INV-BADGES-THINKING-DAY-2020', 'BADGES', 'Thinking Day 2020', 'BADGES', 10, 10, 977, NULL, NULL, 977),
  ('INV-BADGES-THINKING-DAY-2024', 'BADGES', 'Thinking Day 2024', 'BADGES', 11, 11, 825, NULL, NULL, 825),
  ('INV-BADGES-THINKING-DAY-2025', 'BADGES', 'Thinking Day 2025', 'BADGES', 11, 11, 719, NULL, NULL, 719),
  ('INV-TWINKLER-ARTWORK', 'TWINKLER', 'Artwork', 'TWINKLER', 1, 1, 126, NULL, NULL, 126),
  ('INV-TWINKLER-BUSY-HAND-OLD', 'TWINKLER', 'Busy Hand (Old)', 'TWINKLER', 1, 1, 105, NULL, NULL, 105),
  ('INV-TWINKLER-CHEERFUL-HELPER', 'TWINKLER', 'Cheerful Helper', 'TWINKLER', 1, 1, 0, NULL, NULL, 0),
  ('INV-TWINKLER-CUSTOMS', 'TWINKLER', 'Customs', 'TWINKLER', 1, 1, 0, NULL, NULL, 0),
  ('INV-TWINKLER-DISCOVER-THE-OUTDOOR', 'TWINKLER', 'Discover the Outdoor', 'TWINKLER', 1, 1, 180, NULL, NULL, 180),
  ('INV-TWINKLER-FILIPINO-SONG-DANCE', 'TWINKLER', 'Filipino Song & Dance', 'TWINKLER', 1, 1, 3, NULL, NULL, 3),
  ('INV-TWINKLER-FILIPINO-TRADITIONS', 'TWINKLER', 'Filipino Traditions', 'TWINKLER', 1, 1, 440, NULL, NULL, 440),
  ('INV-TWINKLER-GREET-MEET', 'TWINKLER', 'Greet & Meet', 'TWINKLER', 1, 1, 93, NULL, NULL, 93),
  ('INV-TWINKLER-HANDY-WORK', 'TWINKLER', 'Handy Work', 'TWINKLER', 1, 1, 5, NULL, NULL, 5),
  ('INV-TWINKLER-I-AM-ME', 'TWINKLER', 'I am Me', 'TWINKLER', 1, 1, 23, NULL, NULL, 23),
  ('INV-TWINKLER-I-AM-NEAT-AND-HEALTH', 'TWINKLER', 'I am Neat and Healthy', 'TWINKLER', 1, 1, 62, NULL, NULL, 62),
  ('INV-TWINKLER-I-CAN-PLANT', 'TWINKLER', 'I Can Plant', 'TWINKLER', 1, 1, 105, NULL, NULL, 105),
  ('INV-TWINKLER-I-CLEAN-PLANET-EARTH', 'TWINKLER', 'I Clean Planet Earth', 'TWINKLER', 1, 1, 64, NULL, NULL, 64),
  ('INV-TWINKLER-I-LOVE-MY-COUNTRY', 'TWINKLER', 'I Love my Country', 'TWINKLER', 1, 1, 277, NULL, NULL, 277),
  ('INV-TWINKLER-I-PRAY', 'TWINKLER', 'I Pray', 'TWINKLER', 1, 1, 6, NULL, NULL, 6),
  ('INV-TWINKLER-JOLLY-HOSTESS', 'TWINKLER', 'Jolly Hostess', 'TWINKLER', 1, 1, 53, NULL, NULL, 53),
  ('INV-TWINKLER-LITTLE-FIRST-AIDER', 'TWINKLER', 'Little First Aider', 'TWINKLER', 1, 1, 188, NULL, NULL, 188),
  ('INV-TWINKLER-MERRY-HIKER', 'TWINKLER', 'Merry Hiker', 'TWINKLER', 1, 1, 203, NULL, NULL, 203),
  ('INV-TWINKLER-OBEY-WARNING', 'TWINKLER', 'Obey Warning', 'TWINKLER', 1, 1, 165, NULL, NULL, 165),
  ('INV-TWINKLER-PERSONAL-SAFETY', 'TWINKLER', 'Personal Safety', 'TWINKLER', 1, 1, 164, NULL, NULL, 164),
  ('INV-TWINKLER-RHYTHM-SOUNDS', 'TWINKLER', 'Rhythm & Sounds', 'TWINKLER', 1, 1, 3, NULL, NULL, 3),
  ('INV-TWINKLER-SAVE-MONEY', 'TWINKLER', 'Save Money', 'TWINKLER', 1, 1, 174, NULL, NULL, 174),
  ('INV-TWINKLER-USE-MONEY-WISELY', 'TWINKLER', 'Use Money Wisely', 'TWINKLER', 1, 1, 200, NULL, NULL, 200),
  ('INV-STAR-BUSY-BEE', 'STAR', 'Busy Bee', 'STAR', 1, 1, 0, NULL, NULL, 0),
  ('INV-STAR-COOK-OUT', 'STAR', 'Cook Out', 'STAR', 1, 1, 281, NULL, NULL, 281),
  ('INV-STAR-FUN-WITH-COLORS', 'STAR', 'Fun with Colors', 'STAR', 1, 1, 450, NULL, NULL, 450),
  ('INV-STAR-GETTING-TO-KNOW', 'STAR', 'Getting To Know', 'STAR', 1, 1, 1, NULL, NULL, 1),
  ('INV-STAR-GOOD-CITIZEN', 'STAR', 'Good Citizen', 'STAR', 1, 1, 364, NULL, NULL, 364),
  ('INV-STAR-HAPPINESS', 'STAR', 'Happiness', 'STAR', 1, 1, 204, NULL, NULL, 204),
  ('INV-STAR-HAPPY-FAMILY', 'STAR', 'Happy Family', 'STAR', 1, 1, 300, NULL, NULL, 300),
  ('INV-STAR-HIKE-OUT', 'STAR', 'Hike out', 'STAR', 1, 1, 13, NULL, NULL, 13),
  ('INV-STAR-HOME-SAFETY', 'STAR', 'Home Safety', 'STAR', 1, 1, 275, NULL, NULL, 275),
  ('INV-STAR-HOMEMAKER', 'STAR', 'Homemaker', 'STAR', 1, 1, 263, NULL, NULL, 263),
  ('INV-STAR-HOSTESS', 'STAR', 'Hostess', 'STAR', 1, 1, 288, NULL, NULL, 288),
  ('INV-STAR-KEEPING-SAFE', 'STAR', 'Keeping Safe', 'STAR', 1, 1, 289, NULL, NULL, 289),
  ('INV-STAR-LOOK-OUT', 'STAR', 'Look Out', 'STAR', 1, 1, 235, NULL, NULL, 235),
  ('INV-STAR-MAKE-AND-DO', 'STAR', 'Make and Do', 'STAR', 1, 1, 457, NULL, NULL, 457),
  ('INV-STAR-MEET-OUT', 'STAR', 'Meet Out', 'STAR', 1, 1, 238, NULL, NULL, 238),
  ('INV-STAR-MINSTREL', 'STAR', 'Minstrel', 'STAR', 1, 1, 488, NULL, NULL, 488),
  ('INV-STAR-MY-CREATOR', 'STAR', 'My Creator', 'STAR', 1, 1, 463, NULL, NULL, 463),
  ('INV-STAR-MY-HOBBY', 'STAR', 'My Hobby', 'STAR', 1, 1, 164, NULL, NULL, 164),
  ('INV-STAR-ONE-FAMILY', 'STAR', 'One Family', 'STAR', 1, 1, 12, NULL, NULL, 12),
  ('INV-STAR-PEN-INK', 'STAR', 'Pen & Ink', 'STAR', 1, 1, 201, NULL, NULL, 201),
  ('INV-STAR-PEOPLE-AND-PLACES', 'STAR', 'People and Places', 'STAR', 1, 1, 457, NULL, NULL, 457),
  ('INV-STAR-PERFORMER', 'STAR', 'Performer', 'STAR', 1, 1, 166, NULL, NULL, 166),
  ('INV-STAR-PRAISE-GOD', 'STAR', 'Praise God', 'STAR', 1, 1, 443, NULL, NULL, 443),
  ('INV-STAR-READER', 'STAR', 'Reader', 'STAR', 1, 1, 275, NULL, NULL, 275),
  ('INV-STAR-SONG-DANCE', 'STAR', 'Song & Dance', 'STAR', 1, 1, 0, NULL, NULL, 0),
  ('INV-STAR-STAR-AIDER', 'STAR', 'Star Aider', 'STAR', 1, 1, 206, NULL, NULL, 206),
  ('INV-STAR-THIS-IS-ME', 'STAR', 'This is Me', 'STAR', 1, 1, 487, NULL, NULL, 487),
  ('INV-STAR-WALK-OUT', 'STAR', 'Walk Out', 'STAR', 1, 1, 765, NULL, NULL, 765),
  ('INV-JUNIOR-INCOME-GENERATING', 'JUNIOR', 'Income Generating', 'JUNIOR', 1, 1, 134, NULL, NULL, 134),
  ('INV-JUNIOR-BEADED-ACCESSORIES-M', 'JUNIOR', 'Beaded Accessories Maker', 'JUNIOR', 1, 1, 300, NULL, NULL, 300),
  ('INV-JUNIOR-BITS-PIECES', 'JUNIOR', 'Bits & Pieces', 'JUNIOR', 1, 1, 460, NULL, NULL, 460),
  ('INV-JUNIOR-CAMPERS', 'JUNIOR', 'Campers', 'JUNIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-JUNIOR-COOK-BADGE', 'JUNIOR', 'Cook Badge', 'JUNIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-JUNIOR-DANCER', 'JUNIOR', 'Dancer', 'JUNIOR', 1, 1, 19, NULL, NULL, 19),
  ('INV-JUNIOR-EMBROIDERER', 'JUNIOR', 'Embroiderer', 'JUNIOR', 1, 1, 1, NULL, NULL, 1),
  ('INV-JUNIOR-EMERGENCY-PREPAREDNE', 'JUNIOR', 'Emergency Preparedness', 'JUNIOR', 1, 1, 372, NULL, NULL, 372),
  ('INV-JUNIOR-EXPLORER', 'JUNIOR', 'Explorer', 'JUNIOR', 1, 1, 489, NULL, NULL, 489),
  ('INV-JUNIOR-FAMILY-COOK', 'JUNIOR', 'Family Cook', 'JUNIOR', 1, 1, 4, NULL, NULL, 4),
  ('INV-JUNIOR-FAMILY-PROJECT', 'JUNIOR', 'Family Project', 'JUNIOR', 1, 1, 300, NULL, NULL, 300),
  ('INV-JUNIOR-FAMILY-TREE', 'JUNIOR', 'Family Tree', 'JUNIOR', 1, 1, 350, NULL, NULL, 350),
  ('INV-JUNIOR-FILIPINO-GAMES', 'JUNIOR', 'Filipino Games', 'JUNIOR', 1, 1, 144, NULL, NULL, 144),
  ('INV-JUNIOR-FILIPINO-HERITAGE', 'JUNIOR', 'Filipino Heritage', 'JUNIOR', 1, 1, 498, NULL, NULL, 498),
  ('INV-JUNIOR-FIRST-AID-KIT', 'JUNIOR', 'First Aid Kit', 'JUNIOR', 1, 1, 242, NULL, NULL, 242),
  ('INV-JUNIOR-GARDENER', 'JUNIOR', 'Gardener', 'JUNIOR', 1, 1, 1, NULL, NULL, 1),
  ('INV-JUNIOR-GOD-IN-NATURE', 'JUNIOR', 'God in Nature', 'JUNIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-JUNIOR-GOOD-GROOMING', 'JUNIOR', 'Good Grooming', 'JUNIOR', 1, 1, 177, NULL, NULL, 177),
  ('INV-JUNIOR-HERITAGE-HUNT', 'JUNIOR', 'Heritage Hunt', 'JUNIOR', 1, 1, 38, NULL, NULL, 38),
  ('INV-JUNIOR-HISTORIAN', 'JUNIOR', 'Historian', 'JUNIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-JUNIOR-HISTORICAL-PLACES', 'JUNIOR', 'Historical Places', 'JUNIOR', 1, 1, 479, NULL, NULL, 479),
  ('INV-JUNIOR-HOSPITALITY', 'JUNIOR', 'Hospitality', 'JUNIOR', 1, 1, 328, NULL, NULL, 328),
  ('INV-JUNIOR-HOUSEKEEPER', 'JUNIOR', 'Housekeeper', 'JUNIOR', 1, 1, 224, NULL, NULL, 224),
  ('INV-JUNIOR-I-AM', 'JUNIOR', 'I Am', 'JUNIOR', 1, 1, 507, NULL, NULL, 507),
  ('INV-JUNIOR-I-BELIEVE', 'JUNIOR', 'I Believe', 'JUNIOR', 1, 1, 460, NULL, NULL, 460),
  ('INV-JUNIOR-KEEPING-FIT', 'JUNIOR', 'Keeping Fit', 'JUNIOR', 1, 1, 275, NULL, NULL, 275),
  ('INV-JUNIOR-KNITTER', 'JUNIOR', 'Knitter', 'JUNIOR', 1, 1, 352, NULL, NULL, 352),
  ('INV-JUNIOR-LOOKING-WIDE', 'JUNIOR', 'Looking Wide', 'JUNIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-JUNIOR-MADE-IN-THE-PHILIPPI', 'JUNIOR', 'Made in the Philippines', 'JUNIOR', 1, 1, 8, NULL, NULL, 8),
  ('INV-JUNIOR-MUSICIAN', 'JUNIOR', 'Musician', 'JUNIOR', 1, 1, 456, NULL, NULL, 456),
  ('INV-JUNIOR-MY-CIVIC-DUTY', 'JUNIOR', 'My Civic Duty', 'JUNIOR', 1, 1, 507, NULL, NULL, 507),
  ('INV-JUNIOR-NEEDLECRAFT', 'JUNIOR', 'Needlecraft', 'JUNIOR', 1, 1, 567, NULL, NULL, 567),
  ('INV-JUNIOR-ONLINE-SAFETY', 'JUNIOR', 'Online Safety', 'JUNIOR', 1, 1, 1, NULL, NULL, 1),
  ('INV-JUNIOR-PAINTER', 'JUNIOR', 'Painter', 'JUNIOR', 1, 1, 476, NULL, NULL, 476),
  ('INV-JUNIOR-PERFORMER', 'JUNIOR', 'Performer', 'JUNIOR', 1, 1, 35, NULL, NULL, 35),
  ('INV-JUNIOR-PHOTOGRAPHER', 'JUNIOR', 'Photographer', 'JUNIOR', 1, 1, 51, NULL, NULL, 51),
  ('INV-JUNIOR-POSTCARD-MAKER', 'JUNIOR', 'Postcard Maker', 'JUNIOR', 1, 1, 300, NULL, NULL, 300),
  ('INV-JUNIOR-SINGER', 'JUNIOR', 'Singer', 'JUNIOR', 1, 1, 36, NULL, NULL, 36),
  ('INV-JUNIOR-SNACK-MAKER', 'JUNIOR', 'Snack Maker', 'JUNIOR', 1, 1, 429, NULL, NULL, 429),
  ('INV-JUNIOR-UNITY-IN-COMMUNITY', 'JUNIOR', 'Unity in Community', 'JUNIOR', 1, 1, 209, NULL, NULL, 209),
  ('INV-JUNIOR-WAGGGS-KNOWLEDGE', 'JUNIOR', 'WAGGGS Knowledge', 'JUNIOR', 1, 1, 1, NULL, NULL, 1),
  ('INV-JUNIOR-WEAVER', 'JUNIOR', 'Weaver', 'JUNIOR', 1, 1, 275, NULL, NULL, 275),
  ('INV-JUNIOR-YOUNG-HISTORIAN', 'JUNIOR', 'Young Historian', 'JUNIOR', 1, 1, 2, NULL, NULL, 2),
  ('INV-SENIOR-A-GIFT-OF-THE-HEART', 'SENIOR', 'A Gift of the Heart', 'SENIOR', 1, 1, 42, NULL, NULL, 42),
  ('INV-SENIOR-A-LOOK-AT-MYSELF', 'SENIOR', 'A Look at Myself', 'SENIOR', 1, 1, 18, NULL, NULL, 18),
  ('INV-SENIOR-BRIDGING-THE-GAP', 'SENIOR', 'Bridging the Gap', 'SENIOR', 1, 1, 189, NULL, NULL, 189),
  ('INV-SENIOR-CANDLE-MAKING', 'SENIOR', 'Candle Making', 'SENIOR', 1, 1, 216, NULL, NULL, 216),
  ('INV-SENIOR-CHRONICLER', 'SENIOR', 'Chronicler', 'SENIOR', 1, 1, 716, NULL, NULL, 716),
  ('INV-SENIOR-COMMUNITY-SERVICE', 'SENIOR', 'Community Service', 'SENIOR', 1, 1, 388, NULL, NULL, 388),
  ('INV-SENIOR-COOKED-FOOD-PRODUCTI', 'SENIOR', 'Cooked Food Production', 'SENIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-SENIOR-CUSTOMS-AND-TRADITIO', 'SENIOR', 'Customs and Traditions', 'SENIOR', 1, 1, 858, NULL, NULL, 858),
  ('INV-SENIOR-DANCE-TO-THE-RHYTHM', 'SENIOR', 'Dance to the Rhythm', 'SENIOR', 1, 1, 465, NULL, NULL, 465),
  ('INV-SENIOR-DIFFERENCES-AND-SIMI', 'SENIOR', 'Differences and Similarities', 'SENIOR', 1, 1, 1, NULL, NULL, 1),
  ('INV-SENIOR-DRAMATIC-PERFORMER', 'SENIOR', 'Dramatic Performer', 'SENIOR', 1, 1, 154, NULL, NULL, 154),
  ('INV-SENIOR-EARTHQUAKE-PREPAREDN', 'SENIOR', 'Earthquake Preparedness', 'SENIOR', 1, 1, 0, NULL, NULL, 0),
  ('INV-SENIOR-ECO-GOOD-TURNS', 'SENIOR', 'Eco-Good Turns', 'SENIOR', 1, 1, 328, NULL, NULL, 328),
  ('INV-SENIOR-ECO-HANDICRAFT', 'SENIOR', 'Eco-Handicraft', 'SENIOR', 1, 1, 309, NULL, NULL, 309),
  ('INV-SENIOR-ECOLOGIST', 'SENIOR', 'Ecologist', 'SENIOR', 1, 1, 3, NULL, NULL, 3),
  ('INV-SENIOR-FAMILY-ADVENTURE', 'SENIOR', 'Family Adventure', 'SENIOR', 1, 1, 495, NULL, NULL, 495),
  ('INV-SENIOR-FAMILY-LINKS', 'SENIOR', 'Family Links', 'SENIOR', 1, 1, 149, NULL, NULL, 149),
  ('INV-SENIOR-FAMILY-OUTREACH', 'SENIOR', 'Family Outreach', 'SENIOR', 1, 1, 729, NULL, NULL, 729),
  ('INV-SENIOR-FOOD-PRODUCTION', 'SENIOR', 'Food Production', 'SENIOR', 1, 1, 126, NULL, NULL, 126),
  ('INV-SENIOR-GROWING-UP', 'SENIOR', 'Growing Up', 'SENIOR', 1, 1, 8, NULL, NULL, 8),
  ('INV-SENIOR-HAM-RADIO', 'SENIOR', 'Ham Radio', 'SENIOR', 1, 1, 1057, NULL, NULL, 1057),
  ('INV-SENIOR-HARMONY-IN-DIVERSITY', 'SENIOR', 'Harmony in Diversity', 'SENIOR', 1, 1, 37, NULL, NULL, 37),
  ('INV-SENIOR-HOME-NURSE', 'SENIOR', 'Home Nurse', 'SENIOR', 1, 1, 3, NULL, NULL, 3),
  ('INV-SENIOR-INTERNATIONAL-TRAVEL', 'SENIOR', 'International Traveller', 'SENIOR', 1, 1, 762, NULL, NULL, 762),
  ('INV-SENIOR-LIFE-SAVER-OUTDOOR-S', 'SENIOR', 'Life Saver & Outdoor Safety', 'SENIOR', 1, 1, 258, NULL, NULL, 258),
  ('INV-SENIOR-LINKS-OF-UNITY', 'SENIOR', 'Links of Unity', 'SENIOR', 1, 1, 886, NULL, NULL, 886),
  ('INV-SENIOR-LOVE-MY-BODY', 'SENIOR', 'Love my Body', 'SENIOR', 1, 1, 181, NULL, NULL, 181),
  ('INV-SENIOR-LOVE-TO-SING', 'SENIOR', 'Love To Sing', 'SENIOR', 1, 1, 51, NULL, NULL, 51),
  ('INV-SENIOR-MONEY-MANAGEMENT', 'SENIOR', 'Money Management', 'SENIOR', 1, 1, NULL, NULL, NULL, 0),
  ('INV-SENIOR-MUSIC-APPRECIATION', 'SENIOR', 'Music Appreciation', 'SENIOR', 1, 1, 212, NULL, NULL, 212),
  ('INV-SENIOR-MY-FAMILY-I', 'SENIOR', 'My Family & I', 'SENIOR', 1, 1, 508, NULL, NULL, 508),
  ('INV-SENIOR-NATIONAL-LANDMARKS', 'SENIOR', 'National Landmarks', 'SENIOR', 1, 1, 155, NULL, NULL, 155),
  ('INV-SENIOR-NEEDLEWORKS', 'SENIOR', 'Needleworks', 'SENIOR', 1, 1, 175, NULL, NULL, 175),
  ('INV-SENIOR-ORNAMENTAL-PLANT', 'SENIOR', 'Ornamental Plant', 'SENIOR', 1, 1, 465, NULL, NULL, 465),
  ('INV-SENIOR-OUTDOOR-ADVENTURE', 'SENIOR', 'Outdoor Adventure', 'SENIOR', 1, 1, 153, NULL, NULL, 153),
  ('INV-SENIOR-OUTDOOR-COOK', 'SENIOR', 'Outdoor Cook', 'SENIOR', 1, 1, 40, NULL, NULL, 40),
  ('INV-SENIOR-OUTDOOR-SAFETY', 'SENIOR', 'Outdoor Safety', 'SENIOR', 1, 1, 4, NULL, NULL, 4),
  ('INV-SENIOR-PERSONAL-SAFETY', 'SENIOR', 'Personal Safety', 'SENIOR', 1, 1, 92, NULL, NULL, 92),
  ('INV-SENIOR-PROUD-FILIPINO', 'SENIOR', 'Proud Filipino', 'SENIOR', 1, 1, 5, NULL, NULL, 5),
  ('INV-SENIOR-PUBLIC-SAFETY', 'SENIOR', 'Public Safety', 'SENIOR', 1, 1, 4, NULL, NULL, 4),
  ('INV-SENIOR-RECOGNIZING-A-CHILD-', 'SENIOR', 'Recognizing a Child''s Needs', 'SENIOR', 1, 1, 403, NULL, NULL, 403),
  ('INV-SENIOR-RECYCLING', 'SENIOR', 'Recycling', 'SENIOR', 1, 1, 195, NULL, NULL, 195),
  ('INV-SENIOR-SEED', 'SENIOR', 'SEED', 'SENIOR', 1, 1, 291, NULL, NULL, 291),
  ('INV-SENIOR-TWINNING-BADGE', 'SENIOR', 'Twinning Badge', 'SENIOR', 1, 1, 647, NULL, NULL, 647),
  ('INV-SENIOR-VISUAL-ARTS', 'SENIOR', 'Visual Arts', 'SENIOR', 1, 1, 9, NULL, NULL, 9),
  ('INV-SENIOR-WE-ARE-CONNECTED-BAD', 'SENIOR', 'We are Connected Badge', 'SENIOR', 1, 1, 239, NULL, NULL, 239),
  ('INV-CADET-A-SIMPLE-ART-ACTIVIT', 'CADET', 'A Simple Art Activities', 'CADET', 1, 1, 76, NULL, NULL, 76),
  ('INV-CADET-ARTS-DAY', 'CADET', 'Arts Day', 'CADET', 1, 1, 0, NULL, NULL, 0),
  ('INV-CADET-CARE-FOR-THE-ENVIRON', 'CADET', 'Care for the Environment', 'CADET', 1, 1, 6, NULL, NULL, 6),
  ('INV-CADET-EARTHQUAKE-PREPAREDN', 'CADET', 'Earthquake Preparedness', 'CADET', 1, 1, 26, NULL, NULL, 26),
  ('INV-CADET-ECO-CANDLE-MAKER', 'CADET', 'Eco Candle Maker', 'CADET', 1, 1, 125, NULL, NULL, 125),
  ('INV-CADET-ECO-FRIENDLY-IDEAS', 'CADET', 'Eco Friendly Ideas', 'CADET', 1, 1, 175, NULL, NULL, 175),
  ('INV-CADET-EMERGENCY-CHECKLIST', 'CADET', 'Emergency Checklist', 'CADET', 1, 1, 0, NULL, NULL, 0),
  ('INV-CADET-FAMILY-TREE', 'CADET', 'Family Tree', 'CADET', 1, 1, 10, NULL, NULL, 10),
  ('INV-CADET-GENDER-AWARENESS', 'CADET', 'Gender Awareness', 'CADET', 1, 1, 154, NULL, NULL, 154),
  ('INV-CADET-HEALTHY-FOOD', 'CADET', 'Healthy Food', 'CADET', 1, 1, 7, NULL, NULL, 7),
  ('INV-CADET-HERITAGE-SITES', 'CADET', 'Heritage Sites', 'CADET', 1, 1, 9, NULL, NULL, 9),
  ('INV-CADET-MUSICAL-ROUTES', 'CADET', 'Musical Routes', 'CADET', 1, 1, 12, NULL, NULL, 12),
  ('INV-CADET-NEW-LIFE-PLAN', 'CADET', 'New Life Plan', 'CADET', 1, 1, 13, NULL, NULL, 13),
  ('INV-CADET-NONTOXIC-CLEANING', 'CADET', 'Nontoxic Cleaning', 'CADET', 1, 1, 6, NULL, NULL, 6),
  ('INV-CADET-ONLINE-HERITAGE-SITE', 'CADET', 'Online Heritage Sites', 'CADET', 1, 1, 1, NULL, NULL, 1),
  ('INV-CADET-ONLINE-MAGAZINE', 'CADET', 'Online Magazine', 'CADET', 1, 1, 75, NULL, NULL, 75),
  ('INV-CADET-PEER-PRESSURE', 'CADET', 'Peer Pressure', 'CADET', 1, 1, 1, NULL, NULL, 1),
  ('INV-CADET-SELF-AWARENESS', 'CADET', 'Self Awareness', 'CADET', 1, 1, 270, NULL, NULL, 270),
  ('INV-CADET-SMALL-BUSINESS', 'CADET', 'Small Business', 'CADET', 1, 1, 12, NULL, NULL, 12)
)
INSERT INTO public.products AS p (sku, name, description, category_id, image_url, size, cost_price, selling_price, stock_quantity, reorder_level, begin_inventory, purchases, sales_units)
SELECT
  d.sku,
  d.product_name,
  NULL,
  c.id,
  NULL,
  d.size,
  COALESCE(d.cost_price, 0),
  COALESCE(d.selling_price, COALESCE(d.cost_price, 0)),
  COALESCE(d.end_inventory, 0),
  10,
  d.begin_inventory,
  d.purchases,
  d.sales_units
FROM inventory_data d
JOIN all_categories c ON c.name = d.category_name
ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  image_url = EXCLUDED.image_url,
  size = EXCLUDED.size,
  cost_price = EXCLUDED.cost_price,
  selling_price = EXCLUDED.selling_price,
  stock_quantity = EXCLUDED.stock_quantity,
  reorder_level = EXCLUDED.reorder_level,
  begin_inventory = EXCLUDED.begin_inventory,
  purchases = EXCLUDED.purchases,
  sales_units = EXCLUDED.sales_units,
  updated_at = NOW();

COMMIT;
