// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

function createSupabaseClient(): SupabaseClient<Database> {
  if (!isSupabaseConfigured) {
    if (import.meta.env.DEV) {
      console.warn(
        "Supabase environment variables are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable live data."
      );
    }

    const message =
      "Supabase client is not configured. Provide VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable database access.";

    const handler: ProxyHandler<unknown> = {
      get() {
        throw new Error(message);
      },
      apply() {
        throw new Error(message);
      },
    };

    return new Proxy({}, handler) as SupabaseClient<Database>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    },
  });
  }

export const supabase = createSupabaseClient();